apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-node
  template:
    metadata:
      labels:
        app: nginx-node
    spec:
      containers:
        - name: nginx-container
          image: wiszenkoigor/cubi:nginx
          ports:
            - containerPort: 80
          args:
            - nginx
            - -g
            - daemon off;
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: custom-config
              mountPath: /etc/nginx/custom.conf
              subPath: custom.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
        - name: custom-config
          configMap:
            name: nginx-configmap
      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location / {
        proxy_pass http://nodeserver:3000;
      }
    }